version: "3.3"
services:
    app:
        container_name: app
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 3000:3000
        networks:
            - default-network
        links:
            - localhost:nginx
    nginx:
        container_name: webserver
        image: nginx
        restart: unless-stopped
        ports:
            - 80:80
        volumes:
            - /etc/nginx/sites-available/default:/etc/nginx/conf.d/default.conf
        networks:
            - default-network
        depends_on:
            - app
networks:
    default-network:
        driver: bridge
